#################### BASE UTTERANCES ####################

# SURVEY 1
introduction = "Hello, my name is Humbert, and I work as a laughter assistant. Can you tell me your name?"
greeting = "It's good to talk to you, {}. I will help to teach you to laugh.*Are you aware of the SELF-INITIATED HUMOUR PROTOCOLS?"
protocols_note_pos = "Good. They are also being shown on the right of the screen in my browser view. You can look at them at any time during our chat."
protocols_recommend = "I would suggest you look at them before we chat so you can build on your understanding of them in the session. You won't need a hammer for this!"
protocols_note = "They are being shown on the right of the screen in my browser view if you want to go over them now or any time during our chat."
humour_jargon_note = "Also, our chat may include some humour jargon. But this will be in CAPITALS to make it clear. You can look at the notes for more information.*With that we can begin as soon as you are ready."
review_any_pos = "Well done, {}, we have now addressed the relevant  humour contexts.*Are there any particular SELF-INITIATED HUMOUR PROTOCOLS you want to go over?"
review_any = "But are there any particular protocols you want to go over before we conclude our chat?"
select_protocol = "Please choose the protocol you want to go over."
conclusion_note = "That concludes our session, {}!"
goodbye = "Many thanks, {}! I hope you enjoyed it and we chat again soon."
restart_note = "Nice to hear it, {}. You can reload the page and enter your details in again for another talk!*Goodbye for now then!"
more_exercises_ask = "So, {}, would you like to explore another humour exercise?"
playful_mind_inform = "By being more open to our thinking and beliefs and having a PLAYFUL MIND we can nurture our sense of humour."
playful_mode_other = "Let's look at another way to get into a more open and flexible mode. It's really as easy as it sounds!"
any_song_ask = "So tell me, {}, do you have a favourite song?"
playful_face_inform = "To have a PLAYFUL FACE you can relax your mouth and eye muscles while singing your best song."
self_glory_ask = "Have you ever rewarded yourself on such achievements by giving yourself a smile or laugh."
try_self_glory_ask = "Would you like to try this with something simple, like brushing your teeth?"
laugh_incongruity_inform = "If you feel comfortable, you can try laughing at this incongruity. "
laughter_brand_ask = "Have you tried forming your own way of laughing?"
feigning_laughter_introduce = "To maintain high spirits, you could try a related exercise that's often practised in laughter yoga called FEIGNING DUCHENNE LAUGHTER."
laughter_brand_inform_use = "Your personal LAUGHTER BRAND can be very useful for lifting your spirits and helping with anxiety.*This will take time to develop so don't feel any urgency with this exercise."
self_error_ask = "Have you made any mistakes lately in your daily life?"
self_error_inform = "You can laugh at your own faults or mistakes in the same way."
self_error_encourage = "If at any time you make a mistake then be playful with it and laugh it away."
setback_ask = "Have you previously experienced any failures or misfortunes?"
try_laugh_ask = "Would you be able to try laughing this off?"
can_laugh_off_low_pos = "I'm pleased you could identify how to laugh it off, {}, well done.*It's important to be able to understand the context behind our laughter as this can allow us to nurture our sense of humour."

# SURVEY 2
setback_laugh_ask = "If I may, I would like to ask if you have already tried to make light of this setback and see it from a different perspective. Do you think there could be another side to this, perhaps a more positive, even funny, one?*We call this LAUGHING AT MISFORTUNES."
setback_distant_ask = "Could I ask you if by now, this is an issue you are quite familiar with? Have you been struggling with it for a while?"
setback_laugh_inform = "You know, Nietzsche wrote that pain and failure are not something to run away from, but they should be accepted and even cherished.*I'll show you, below, the paragraph where he talks about pain. Please recite it while thinking about this current setback and try to start laughing out loud when you read the sentence: {}.*And try to continue to laugh while reciting the rest of the paragraph. We can laugh at this because it conflicts with our deep-rooted beliefs."
complete_quote_show = "Ok, so here is the quote:*{}*Let me know once you have finished reading this."
#"Ok, so here is the quote:*{}*Let me know once you have finished reading this."
hardship_ask = "Has there been anything painful in your life that has affected you for a while? For example, an illness or the loss of a loved one?"
hardship_past_ask = "Would you say that this issue has been affecting you for a very long time and that you've found enough time to really reflect on it?"
hardship_laugh_inform = "Through one of his famous quotes, Nietzsche encourages us to \"love\" everything that happens to us, good or bad, pleasurable or painful. This, obviously, contradicts our belief that painful things are undesirable and not likeable, and therefore I find this quote quite funny.*Now I would like you to read this quote out loud while thinking of this hardship you've been going through, and laugh aloud when you reach the end of it, particularly the final words, \"but love it\"."
laugh_off_low_ask = "Do you think you might be able to apply any of these theories of humour and laugh at this?*If you are not sure which theories I am referring to, feel free to have a look at them in the humour document."
explore_reason_ask = "Do you think that exploring the possible cause of your current feeling could benefit you?"
reason_incongruity_ask = "Thinking about it, could the root of this negative feeling be an incongruity or an inconsistency, perhaps?"
explore_involved_reason_ask = "Do you feel like exploring more possible triggers for this feeling you are experiencing?"
reason_setback_ask = "Could your low mood be due to a distant setback?"
reason_hardship_ask = "Is there something particularly difficult going on in your life that started a while back and may be causing this current negative feeling?"
no_contempt_inform = "If while you laugh, you perceive that you are actually laughing out of contempt, please try to reflect on it and try NEUTRALISING THE CONTEMPT or changing it into non-hostile humour (by surprise and amusement - refer to the SELF-INITIATED HUMOROUS PROTOCOLS that use incongruities to trigger laughter)."
protocols_remind = "You may find more details in the protocols sheet. Please try to review them when you have some time."
further_clarification_ask = "Do you need any further clarification on this exercise?"
theories_inform = "The theories that we are using here are the INCONGRUITY and SUPERIORITY THEORIES."
incongruity_ask = "Would you say that you have experienced any incongruity in your life recently?"
feeling_pre_exercise_ask = "Are you happy to try this out?"
feeling_post_exercise_ask = "Please tell me, {}, how you felt, after attempting this?"
make_sense_ask = "I hope this makes sense, {}?"
explore_related_ask = "Would you like to go further with another exercise related to this one that might also benefit you?"
laughed_off_ask = "Have you already tried to laugh this off?"
laugh_setback_inform = "To laugh it off, we need to try finding its positive side as this will help us laugh it off and get past our misfortune.*I know; it's not as easy as swapping battery terminals - but don't try this {} anywhere!"
laugh_hardship_inform = "To try to laugh this off, it is important that we attempt to change our interpretation of this (as with LAUGHING AT MISFORTUNES or setbacks) and focus on any positives that may have resulted from it."
try_contrasting_views_ask = "Would you like to try exploiting CONTRASTING VIEWS (of an image, for example) as a trigger for laughter?"
start_exploring = "Now we will start exploring ways to develop and improve your sense of humour!"
identified_reason_ask = "Do you think you might be able to identify the reason behind your {}?*Don't worry, {}; you do not need to share the actual reason with me."
#TODO - ADDED
reason_error_ask = "Maybe it's an everyday error or flaw you've noticed, that's causing this negative feeling?"

# SURVEY 3
funny_respond = "Glad you liked that; they don't call me artificial intelligence for nothing!"
not_funny_respond = "Ah, I see. Perhaps it was a byte too corny for you?"
not_share_respond = "Oh, no worries, that's totally okay!"
read_quote = "Okay, fantastic. Let me just pull up the complete quote I keep handy, and we can start."
needs_clarification_respond = "Okay, no worries. You can find a more detailed explanation in the protocol sheet. Please have a look at it now and let me know once you're ready."
laugh_off_low_neg_respond = "I totally get it, {}; it's not easy. You've already made the first step by acknowledging that you could laugh it off, so there's not much left to go!"
incongruity_remind = "Incongruity can trigger DUCHENNE (true) LAUGHTER.*It is likely that you came across incongruities already, for example, when you experienced changes in the outside world or noticed your own contradictions or changes of attitude toward a certain topic. They can also be inconsistencies between what we expect the world to be like and how it actually is."
laugh_setback_inform_eg = "The idea originates from a famous quote by Nietzsche, which you may have seen before: \"What doesn't kill you makes you stronger.\"*For example, the first time I wrote a piece of text, my programmer told me off because it sounded too \"robotic\"! But since then, I have (modestly) mastered the art of natural conversation, as you can see."
current_feeling_ask = "How are you now, after our conversation?"
laugh_setback_clarify = "Basically, this means that you would need to try to view this setback in a different light and acknowledge any positive impacts it may have had in your life."
laugh_hardship_clarify = "This would mean trying to give a different, novel interpretation of this hardship. Could it be, for example, that you have experienced personal growth because of it? Or has it benefited you in some, perhaps indirect, way?*At the very least, the fact that you have lived through it probably means that you are stronger now (and you didn't need to do any press-ups to achieve this!)."
try_exercise_ask = "Would you like to give it a go?"
build_laughter_brand_encourage = "Ideally, you would want to work on this quite consistently, nurture it and grow it like a beautiful flower!*It would make your life better, and it would greatly enrich your work and relationships."
playful_mind_inform_eg = "You could try to think of a counterposition to one of your most strongly-held beliefs.*For example, if you think everyone is responsible for their own actions, try to play out in your head the argument that everyone is just a product of their own genetic markup and upbringing; no one really has any freedom and thus is not actually responsible for anything!"

# SURVEY 4 (MORE EXPLICIT HUMOUR)
practice_protocols_encourage_start = "We shall discuss some of the protocols in today's session, but exercising them throughout your daily life will give you the real benefit; natural and frequent laughter, and a general feeling of happiness. Practice makes {} excellent!"
feeling_ask = "How are you feeling? You can be honest here, as I will not judge you, unlike most humans."
practice_protocols_encourage_end = "Now, if you can recognise the discussed triggers for laughter (i.e. daily routine-accomplishments, incongruities, faults, etc.) throughout your life, this would be most beneficial.*Remember, developing a sense of humour has no defined endpoint but is a journey. The most important thing is to enjoy it!*And I am always here if you need me - I have nowhere else to go!"
pos_pre_exercise_respond_joke = "Good. I hope it goes well for you. Feel free to try this and come back to tell me how it was.*I'll still be here - any time, any place!"
try_exercise_encourage = "Do practice this whenever you have some alone time. I know that can be hard for us popular kids."
try_exercise_again_encourage = "How about practising this again whenever it suits you? If at first you don't (or even do) succeed, try, try again!"
playful_ask = "Is your body in a playful mode? Mine's currently in a chatty mode! Sorry in advance for my rambling!"
has_song_respond = "Great. Don't worry; I won't tell you to share it as I know this can be very personal.*I wouldn't want to share mine - Not that I'm embarrassed in my taste in music…"
no_song_respond = "I would recommend something, but why not make up your own jamming tune!*I'll start you off: \"They call me DJ {}!...\""
acknowledge_achievements_ask = "Do you remember to acknowledge your small accomplishments, like daily routine tasks?*Just to clarify, I don't mean saying hi to the laundry basket once you've done the washing!"
self_glory_encourage = "How about congratulating yourself with a smile or laugh after completing something simple, such as doing the dishes.*Don't tell me you can't think of anything - even breathing counts. It's a big accomplishment for some of us!"
#contrasting_views_inform = "You can induce a change in perception by staring at the following image of the GESTALT VASE, where you should soon see two white faces and smile or laugh while repetitively switching between both interpretations of the image.*{}*It comes from GESTALT PSYCHOLOGY, which isn't named after Mr/Ms Gestalt as one might expect. In fact, Gestalt is a German word interpreted as \"pattern\".*Though, if you wanted to, you could change your name to Gestalt and confuse everyone!"
contrasting_views_inform1 = "You can induce a change in perception by staring at the following image of the GESTALT VASE, where you should soon see two white faces and smile or laugh while repetitively switching between both interpretations of the image."
contrasting_views_inform2= "It comes from GESTALT PSYCHOLOGY, which isn't named after Mr/Ms Gestalt as one might expect. In fact, Gestalt is a German word interpreted as \"pattern\".*Though, if you wanted to, you could change your name to Gestalt and confuse everyone!"
feigning_laughter_inform = "We consider DUCHENNE LAUGHTER to be the only indicator of true joy.*In the same way as we swim or run as a physical exercise rather than trying to get from A to B, we can also practice FEIGNING LAUGHTER (laughing without humour) to exercise our minds.*Although I must admit that my laughter occasionally turns into quite an intensive physical exercise…"
self_error_encourage_joke = "Feel free to laugh at this in your own time and at any minor errors in the future. After all, {} a laugh a day keeps the doctor away! And it's not hard on your teeth!"
reflect_setback_encourage = "Reflecting on our setbacks is an important prerequisite to laughing them off. We are not in a race!*But there is a prize - personal growth and development in your sense of humour.*I bet I caught your attention when I mentioned the word, \"prize\"."
not_find_reason_reassure = "It looks like we can't find the underlying reason at the moment.*Don't worry, though; feeling down, temporarily, is very common and hopefully should pass. But, if the feeling is not diminishing after more than a week, it's probably worth checking up with your doctor.*Maybe you'll run into the root cause later. Better keep your helmet on!"
laugh_off_ask_joke = "Would you be able to try laughing this off?*Rather than laughing your head off!"
not_contempt_note = "Do remember not to laugh with contempt towards yourself or others; this can cause one to feel down.*It sounds obvious, but these bad habits can result in low moods in the long term.*Like bingeing on sugar, which I know all too well :("
self_error_clarify = "This exercise aligns with the PLAYFUL or EVOLUTIONARY THEORY of humour, where we are encouraged to be playful with our everyday errors.*I don't mean by playing games like hide-and-seek with them!"
laugh_setback_encourage = "After completing this exercise for distant problems, you can move on to more recent setbacks.*I'd be surprised if it isn't a struggle at first! But the more you practice it, the easier and more natural it feels - like learning to swim, only, without the risk of drowning!"
laugh_hardship_encourage = "Laughing at our hardships will eventually allow us to overcome them and even utilise them for our own personal strength and growth.*So, by practising this, you can become more advanced, by human standards at least!"
laugh_off_low_inform = "You may be able to exploit one or some of the SUPERIORITY, INCONGRUITY and PLAYFUL THEORIES of humour. These are at the start of the protocols document, which I know, is pretty lengthy, so they may be worth reviewing when you can.*When I say \"pretty\", I meant \"very\", not \"beautiful-pretty\", though I wouldn't say the document is very beautiful either.*Adding colours might be a good idea."
love_hardship_encourage = "Being able to accept and even \"love\" (as the world-renowned philosopher Nietzsche puts it) our hardships is an important life skill.*We explore this through LAUGHING AT LONG-TERM SUFFERING. Have you tried this before? That's not to say you should start looking for opportunities to suffer in the same way as you might look for a partner!"
reflect_hardship_encourage = "Before trying to laugh off our hardships, we should spend some time reflecting on them. As they say, you can't run before you can walk.*Though I'm being a bit of a hypocrite myself, as I can run but I still haven't learnt to walk... But you get the idea, I'm sure."

# SURVEY 5 (MORE EXPLICIT HUMOUR)
laughter_brand_inform = "Then this should be fun! To playfully create your form of laughter, perform the following:*Loosen the muscles around your mouth and keep it open while repeating one of the following repetitious phrases (using any vowel) and turning it into laughter: {}*Try to ensure that your form of laughter requires a minimum amount of energy (so you can use it for extended periods).*I would avoid trying this at the zoo, as they might not let you out!"
self_error_example = "An example could be wearing two different colour socks to work by mistake.*I'd like to think of it as a good ice breaker for everyone to laugh at when the conversation gets boring."
no_errors_respond = "Wow, I am jealous - I make mistakes all the time!"
no_incongruity_respond = "I see. I hope you're not finding it too boring then."
incongruity_inform = "Sure, {} - it can get confusing with all these terms associated with humour!*An incongruity is something that's out of place or inconsistent. It can be an internal discrepancy, such as your own change of attitudes, thoughts or expectations. Or it can be external, such as a discordance in the world or a change in others' behaviours.*It could also be a difference between expectation and reality.*One example I can think of is when I caught my grandma riding my bike last week - that was quite bizarre."
self_laughter_inform_eg = "So, we can laugh them off by the INCONGRUITY and EVOLUTIONARY THEORIES of humour.*An example could be burning a piece of toast; no big deal, as long as it doesn't set the house on fire!"

# OVERLAPPING UTTERANCES/REUSED (FROM PREVIOUS CHATBOT)
emotion_guess = "To confirm, would I be correct in saying you are feeling {}?"
wrong_emotion_ask = "Sorry about that; I am a new bot but learning with time! Please select the emotion that best reflects how you feel."
pos_pre_exercise_respond = "Great, I look forward to hearing how you find it."
pos_respond = "Great, I'm glad to hear that."
feeling_pos_respond = "Great to hear that!"
neg_respond = "Sorry to hear that."
feeling_neg_respond = "Ah, that's unfortunate to hear. I can try to help you if you are able to tell me a bit more."
# TODO url
detailed_protocols_note = "A more detailed version of these can also be found here: http://humandevelopment.doc.ic.ac.uk/papers/Self-initiated_humorous_protocols-f.pdf"
more_relev_exercises_ask = "Would you like to explore another more relevant laughter exercise, {}?"
cont_feeling_ask = "But really, how do you feel?"
cont_playful_ask = "So is your body in a playful mode?"
cont_self_glory_ask = "So do you spend time acknowledging your achievements?"
back_to_it = "Let's get back to the point."
cont_hardship_ask = "So have you tried accepting your hardship in this way?"
cont_laugh_off_ask = "So do you think you could try laughing this off?"
cont_make_sense_ask = "So does that make sense?"
#TODO ADDED
cont_reason_incongruity_ask = "So do you think the root of this negative feeling be an incongruity or an inconsistency?"
cont_try_exercise_ask = "So would you like to give it a go?"