#!/bin/bash

cd ..
python3 -m virtualenv ./HumBERT
cd ./HumBERT
source bin/activate
cd ./model/
python3 -m pip install -r requirements.txt
set FLASK_APP=flask_backend_with_aws
flask db init
flask db migrate -m "testDB table"
flask db upgrade
# $ nano .env ----> add DATABASE_URL="sqlite:////YOUR LOCAL PATH TO THE app.db FILE" to the .env file, save and exit
export FLASK_DEBUG=1 # to run in debug mode
flask run
